const:
  default-page-size: 20
  auth-code-length: 6

file:
  directory: D:/2024-02/download/greengram_ver3

domain:
  path:
    server: http://112.222.157.156:5234/

mybatis:
  mapper-locations: mappers/**/*.xml


kakaopay:
  secretKey:
  cid: TC0ONETIME

jwt-const:
  issuer: green@green.kr
  secret: DaeguGreenArtAcademyClass502RoomForJavaSpringBootFightingD23sdfsdf23
  header-schema-name: Authorization
  claim-key: signedUser
  token-name: JWT
  token-type: Bearer
  access-token-expiry: 600_000_000 #10분(MS)
  refresh-token-expiry: 1_296_000_000 #15일(MS)
  refresh-token-cookie-name: refresh-token
  refresh-token-cookie-expiry: 1_296_000 #15일 (S)




spring:


  application:
    name: Jobone
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mariadb://localhost/job_done
    username: root
    password: green502
  servlet:
    multipart:
      max-file-size: 15MB
  jpa:
    database: mysql
    hibernate:
      #ddl-auto: create #entity를 서버 기동때마다 drop 후 create 한다.
      ddl-auto: update #entity가 없으면 create, 기존 존재하는 entity는 컬럼을 새롭게 추가하는 것만 반영
    properties:
      hibernate:
        jdbc:
          batch_size: 50
        format_sql: true
        order_updates: true
    show-sql: true


springdoc:
  swagger-ui:
    default-model-expand-depth: 10
    display-request-duration: true
    groups-order: asc
    operations-sorter: method
    path: /swagger
    tags-sorter: alpha
  cache:
    disabled: true


mail:
  host: smtp.gmail.com
  port: 587
  username: "tlaqhdbs12@gmail.com"
  password: "uxds thkj vsvs clpv"
  properties:
    mail:
      smtp:
        auth: true
        starttls:
          enable: true
          required: true
        connectiontimeout: 5000
        timeout: 5000
        writetimeout: 5000
  auth-code-expiration-millis: 1800000