const:
  default-page-size: 20
  auth-code-length: 6

file:
  directory: D:\sys\USER\IdeaProjects\2ndProject\jobdone


mybatis:
  mapper-locations: mappers/**/*.xml


kakaopay:
  secretKey:
  cid: TC0ONETIME

jwt-const:
  issuer: green@green.kr
  secret: DaeguGreenArtAcademyClass502RoomForJavaSpringBootFightingD23sdfsdf23
  header-schema-name: Authorization
  claim-key: signedUser
  token-name: JWT
  token-type: Bearer
  access-token-expiry: 600_000 #10분(MS)
  refresh-token-expiry: 1_296_000_000 #15일(MS)
  refresh-token-cookie-name: refresh-token
  refresh-token-cookie-expiry: 1_296_000 #15일 (S)




spring:
  application:
    name: JobDone
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mariadb://localhost/job_done
    username: root
    password: qwerr130
  servlet:
    multipart:
      max-file-size: 15MB


springdoc:
  swagger-ui:
    default-model-expand-depth: 10
    display-request-duration: true
    groups-order: asc
    operations-sorter: method
    path: /swagger
    tags-sorter: alpha
  cache:
    disabled: true


mail:
  host: smtp.gmail.com
  port: 587
  username: "tlaqhdbs12@gmail.com"
  password: "lazk ajix khro gjpg"
  properties:
    mail:
      smtp:
        auth: true
        starttls:
          enable: true
          required: true
        connectiontimeout: 5000
        timeout: 5000
        writetimeout: 5000
  auth-code-expiration-millis: 1800000