file:
  directory: /home/download/jobdone/image

spring:
  datasource:
    url: jdbc:log4jdbc:mariadb://192.168.0.144:3306/db_even_last_4?serverTimezone=Asia/Seoul
    username: even_last_4
    password: keystone
#server:
#  ssl:
#    key-store: classpath:job-done.r-e.kr.pfx
#    key-store-type: PKCS12
#    key-password: ${SSL.KEY}
#    key-store-password: ${SSL.KEY}
#  tomcat:
#    redirect-context-root: true

